# Generated by Django 3.1.7 on 2021-04-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='Ru',
        ),
    ]
