# Generated by Django 3.1.7 on 2021-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0003_auto_20210405_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='SM_Csc',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
