# Generated by Django 3.2 on 2021-04-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0004_inventaire_sm_csc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='Moniteur',
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='Date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='heure',
            field=models.CharField(max_length=50),
        ),
    ]
