# Generated by Django 3.2 on 2021-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0006_auto_20210406_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
