# Generated by Django 3.2 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0007_inventaire_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
