# Generated by Django 3.1.7 on 2021-04-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0008_inventaire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=None, blank=True, max_length=50, null=True),
            preserve_default=False,
        ),
    ]
