# Generated by Django 3.1.7 on 2021-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0009_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
