# Generated by Django 3.1.7 on 2021-04-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0010_auto_20210412_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
