# Generated by Django 3.1.7 on 2021-04-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='statut',
        ),
    ]
