# Generated by Django 3.1.7 on 2021-04-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0013_auto_20210412_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
