# Generated by Django 3.2 on 2021-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0014_inventaire_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('Nombre_De_Bac', models.CharField(blank=True, max_length=50, null=True)),
                ('Zone_De_Kit', models.CharField(blank=True, max_length=50, null=True)),
                ('SM_Csc', models.CharField(blank=True, max_length=50, null=True)),
                ('Code_condi', models.CharField(blank=True, max_length=50, null=True)),
                ('QTe_Uc', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('heure', models.CharField(blank=True, max_length=50, null=True)),
                ('Moniteur', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('Anticipation', models.CharField(blank=True, max_length=50, null=True)),
                ('Au_Débord', models.CharField(blank=True, max_length=50, null=True)),
                ('Commenataire', models.CharField(blank=True, max_length=50, null=True)),
                ('HFA', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
