# Generated by Django 3.2 on 2021-04-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0016_auto_20210417_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Ru',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
