# Generated by Django 3.2 on 2021-04-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0017_auto_20210417_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertes',
            name='Anticipation',
        ),
        migrations.RemoveField(
            model_name='alertes',
            name='Au_Débord',
        ),
    ]
