# Generated by Django 3.2 on 2021-05-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0018_auto_20210420_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='BDL',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='Crossdock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='Id_Appro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='Nom_Appro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='Prénom_Appro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='Quai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
