# Generated by Django 3.1.7 on 2021-05-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0020_auto_20210524_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertes',
            name='SDate',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='SDate',
        ),
    ]
