# Generated by Django 3.1.7 on 2021-05-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0022_auto_20210524_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
