# Generated by Django 3.2.4 on 2021-06-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0023_membership_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emplacement_SM', models.CharField(blank=True, max_length=50, null=True)),
                ('Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('Nb_bacs', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_heure', models.CharField(blank=True, max_length=50, null=True)),
                ('Travee_debord', models.CharField(blank=True, max_length=50, null=True)),
                ('Conditionnement_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('Qt_pieces_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('Appro', models.CharField(blank=True, max_length=50, null=True)),
                ('Fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('CMJ', models.CharField(blank=True, max_length=50, null=True)),
                ('FDS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
