# Generated by Django 3.2.4 on 2021-07-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0024_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_Emplacement_SM', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Conditionnement_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Qt_pieces_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Appro', models.CharField(blank=True, max_length=50, null=True)),
                ('M_Fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('M_CMJ', models.CharField(blank=True, max_length=50, null=True)),
                ('M_FDS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='Nb_bacs',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
