# Generated by Django 3.2.5 on 2021-07-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0025_auto_20210701_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emplacement_SM', models.CharField(blank=True, max_length=50, null=True)),
                ('Reference', models.CharField(blank=True, max_length=50, null=True)),
                ('Nb_bacs', models.IntegerField(blank=True, null=True)),
                ('Date_heure_entrée', models.CharField(blank=True, max_length=50, null=True)),
                ('Travee_debord', models.CharField(blank=True, max_length=50, null=True)),
                ('Conditionnement_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('Qt_pieces_UC', models.CharField(blank=True, max_length=50, null=True)),
                ('Appro', models.CharField(blank=True, max_length=50, null=True)),
                ('Fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('CMJ', models.CharField(blank=True, max_length=50, null=True)),
                ('FDS', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_heure_sortie', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='Nb_bacs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
