# Generated by Django 3.2.5 on 2021-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GA_UEP', '0027_esstock_esdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='StDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
